# Numpy

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

In [ ]:
import numpy as np

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [ ]:
base = np.loadtxt('minutes_n_ingredients.csv', skiprows=1, delimiter=',', dtype=np.int32)
print(base[:5, :])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
rec_mean = np.mean(base[:, 1:], axis=0)
print(rec_mean)

[2.16010017e+04 9.05528000e+00]


In [ ]:
rec_min = np.amin(base[:, 1:], axis=0)
print(rec_min)

[0 1]


In [ ]:
rec_max = np.amax(base[:, 1:], axis=0)
print(rec_max)

[2147483647         39]


In [ ]:
rec_median = np.median(base[:, 1:], axis=0)
print(rec_median)

[40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [ ]:
q = np.quantile(base[:, 1], 0.75)
print(q)

65.0


In [ ]:
base[:,1] = np.clip(base[:, 1], None, q)

In [ ]:
# вывод итогового массива
print(base)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:
equal_zero = np.count_nonzero(base[:,1]==0)
print(equal_zero)

479


In [ ]:
base[:,1][base[:,1] == 0] = 1
# вывод измененного массива
print(base) 
# вывод количества строк с 0 продолжительностью
print(np.count_nonzero(base[:,1]==0))

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]
0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
num_unique = len(np.unique(base[:,:], axis=0))
print(num_unique)
# так как все id различны - рассматриваем 2 и 3 столбцы
num_unique = len(np.unique(base[:,1:], axis=0))
print(num_unique)

100000
1135


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
n_ingridiens, n_n = np.unique(base[:,2], return_counts=True)
# можно вывести и так, но этот вывод удобнее
unique_ingridients = np.full((len(n_ingridiens), 2), 0, dtype=np.int32)
unique_ingridients[:,0] = n_ingridiens
unique_ingridients[:,1] = n_n
print(unique_ingridients)

[[    1    13]
 [    2   926]
 [    3  2895]
 [    4  5515]
 [    5  7913]
 [    6  9376]
 [    7 10628]
 [    8 10951]
 [    9 10585]
 [   10  9591]
 [   11  8297]
 [   12  6605]
 [   13  4997]
 [   14  3663]
 [   15  2595]
 [   16  1767]
 [   17  1246]
 [   18   790]
 [   19   573]
 [   20   376]
 [   21   217]
 [   22   161]
 [   23   105]
 [   24    69]
 [   25    50]
 [   26    28]
 [   27    16]
 [   28    16]
 [   29    12]
 [   30    12]
 [   31     3]
 [   32     1]
 [   33     2]
 [   34     1]
 [   35     3]
 [   37     1]
 [   39     1]]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
new = base
res = new[new[:,2] <= 5]
# вывод размера измененного массива
print(res.shape)
# вывод измененного массива
print(res)

(17262, 3)
[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
ar_minutes = base[:, 1]
ar_ingridients = base[:, 2]
ar_divided = np.divide(ar_ingridients, ar_minutes)
# print(ar_divided)
divided = np.sort(ar_divided)
print(divided[-1])

24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
minutes_sorted = base[base[:, 1].argsort()]
top_100 = minutes_sorted[-100:, :]
np.mean(top_100[:, 2])

9.96

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
ids = np.random.choice(base[:,0], size=10, replace=False)
mask = np.isin(base[:,0], ids)
print(base[mask])

[[144665     65      7]
 [322349      2      5]
 [312370     25     13]
 [203931     25      5]
 [111813     65      6]
 [115765     65      8]
 [267142      5      9]
 [263742     15     12]
 [230014     60     10]
 [148743     65     10]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
less_mean = np.count_nonzero(base[:,2] < rec_mean[1])
percent_less_mean = less_mean / len(base[:,2]) * 100
print(percent_less_mean)

58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
show_easy = np.full((len(base[:,1]), 4), 0, dtype=np.int32)
show_easy[:, :3] = base;
show_easy[:, 3] = np.where((show_easy[:, 1]<=20) & (show_easy[:, 2] <= 5), 1, 0)
# вывод массива со значениями простого/сложного рецептов
print(show_easy)
# вывод количества простых рецeптов
easy_number = np.count_nonzero(show_easy[:,3]==1)
print(easy_number)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993     65     14      0]]
9552


13. Выведите процент "простых" рецептов в датасете

In [ ]:
percent_easy = easy_number / len(base[:,2]) * 100
print(percent_easy)

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [ ]:
show_shortness = np.full((len(base[:,1]), 6), 0, dtype=np.int32)
show_shortness[:, :3] = base;
show_shortness[:, 3] = np.where((show_shortness[:, 1]<10), 1, 0)
show_shortness[:, 4] = np.where((show_shortness[:, 1] >= 10) & (show_shortness[:, 1] < 20), 1, 0)
show_shortness[:, 5] = np.where((show_shortness[:, 1]>=20), 1, 0)
# вывод массива,где столбец 4 - значения меньше 10, 5 - от 10 до 20, 6 - от 20
#print(show_shortness)
groups_amount = np.zeros(3)
#считаем количество элементов в каждой группе
groups_amount[0] = np.count_nonzero(show_shortness[:,3]==1)
groups_amount[1] = np.count_nonzero(show_shortness[:,4]==1)
groups_amount[2] = np.count_nonzero(show_shortness[:,5]==1)
# сортируем список. нулевой элемент - наименьший
groups_amount = groups_amount[groups_amount[:].argsort()]
# создаем массив нужной размерности
array_3d = np.zeros ((3, int(groups_amount[0]), 3), dtype=np.int32)
# заполняем массив
array_short_all = show_shortness[show_shortness[:, 3] != 0]
array_standart_all = show_shortness[show_shortness[:, 4] != 0]
array_long_all = show_shortness[show_shortness[:, 5] != 0]
array_short = array_short_all[:int(groups_amount[0]), :]
array_standart = array_standart_all[:int(groups_amount[0]), :]
array_long  = array_long_all[:int(groups_amount[0]), :]
array_3d[0, :, :] = array_short[:, :3]
array_3d[1, :, :] = array_standart[:, :3]
array_3d[2, :, :] = array_long[:, :3]
print(array_3d.shape)

(3, 7588, 3)
